---
- name: Create dozzle container
  community.docker.docker_container:
    name: dozzle
    image: amir20/dozzle
    pull: true
    state: started
    detach: yes
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
