---
- name: Create dozzle container
  community.docker.docker_container:
    name: "{{ container_name }}"
    hostname: "{{ container_name }}"
    image: "{{ image }}"
    pull: true
    state: started
    detach: yes
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    env: "{{ env }}"
    volumes: "{{ volumes }}"
    network_mode: internal
    networks: "{{ networks }}"
