---
- hosts: servers

  vars_files:
    - defaults/main.yaml

  remote_user: "{{ system_user }}"
  become: true
  gather_facts: true

  roles:
    - role: host
      tags:
        - provision-host
    - role: user
      tags:
        - provision-host
    - role: docker
      tags:
        - provision-host
    - role: argon-one
      tags:
        - provision-host
    - role: nginx-proxy-manager
      tags:
        - core-services
    - role: pihole
      tags:
        - core-services
    - role: cloudflared
      tags:
        - core-services
    - role: watchtower
      tags:
        - core-services
    - role: dozzle
      tags:
        - core-services
    - role: syncthing
      tags:
        - services
