---
- name: Create watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    state: started
    detach: yes
    restart_policy: unless-stopped
    container_default_behavior: compatibility
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
